api_login_check:
    path: /api/login_check

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# like_publication:
#     path: /les-publications/addLike/{id}
#     controller: App\Controller\PublicationController::like

user_can_ban_comment:
    path: /les-publications/ban/{idComment}
    controller: App\Controller\PublicationController::userCanBanComment

user_can_ban_user:
    path: /les-publications/ban/user/{idUser}
    controller: App\Controller\PublicationController::userCanBanUser

user_add_friend:
    path: /mon-profil/friends/add/{idUserReceive}/{idUserSender}
    controller: App\Controller\UserFriendController::userAddFriend

user_delete_friend:
    path: /mon-profil/mes-amis/delete/{idRelationShip}
    controller: App\Controller\UserFriendListController::userDeleteFriend

user_delete_invitation:
    path: /mon-profil/invitations/delete/{idRelationShip}
    controller: App\Controller\UserFriendController::userDeleteInvitation

user_accepte_invitation:
    path: /mon-profil/invitations/accept/{idRelationShip}
    controller: App\Controller\UserFriendController::userAddInvitation

user_show_participant_group:
    path: /mon-profil/groupes/show/{idGroup}
    controller: App\Controller\UserManageGroupsController::showParticipantGroup

user_delete_group:
    path: /mon-profil/groupes/delete/{idGroup}
    controller: App\Controller\UserManageGroupsController::deleteGroup

user_add_participant_group:
    path: /mon-profil/groupes/add/{idGroup}/addUser/{idUser}
    controller: App\Controller\UserManageGroupsController::addParticipantInGroup

user_delete_participant_group:
    path: /mon-profil/groupes/delete/user/{idUserBelongGroup}
    controller: App\Controller\UserManageGroupsController::deleteParticipantInGroup

user_participe_event:
    path: /evenements/ajout/{idEvent}
    controller: App\Controller\EventController::addParticipantInEvent

user_send_message:
    path: /mon-profil/messages/{id}
    controller: App\Controller\UserCommunicatesController::userSendMessages

user_send_message_group:
    path: /mon-profil/messages/group/{idGroup}
    controller: App\Controller\UserCommunicatesController::userSendMessagesInGroup
# Routes Admin
delete_comments:
    path: /admin/comments/delete/{idComment}
    controller: App\Controller\Admin\AdminCommentsController::deleteComment

cancel_reported_comments:
    path: /admin/comments/cancelReported/{idComment}
    controller: App\Controller\Admin\AdminCommentsController::cancelReportedComment

delete_themes:
    path: /admin/themes/delete/{idTheme}
    controller: App\Controller\Admin\AdminThemesController::deleteThemes

