api_login_check:
    path: /api/login_check

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

user_add_friend:
    path: /mon-profil/friends/{idUserReceive}/{idUserSender}
    controller: App\Controller\UserFriendController::userAddFriend
